"""empty message

Revision ID: 133c0d34caa6
Revises: 168c1d5a0bef
Create Date: 2021-09-22 19:54:31.965384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '133c0d34caa6'
down_revision = '168c1d5a0bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('favorite_id', sa.Integer(), nullable=False))
    op.drop_column('favorites', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('favorites', 'favorite_id')
    # ### end Alembic commands ###
