"""empty message

Revision ID: 168c1d5a0bef
Revises: 134f040dfcb7
Create Date: 2021-09-22 19:15:36.809731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '168c1d5a0bef'
down_revision = '134f040dfcb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'starship',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'homeworld',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'homeworld',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'starship',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
